In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import StratifiedShuffleSplit, ShuffleSplit
import secrets     

In [28]:
#load data from 2d and 3d landmarks 

#start with BBP
Data_3D = pd.read_csv(r"C:\Users\GuarinD\Documents\GitHub\Face_and_Gestures_2020\data\NewFeatures2d_BIGSMILE.csv", index_col=0)
#Data_2D = pd.read_csv(r"C:\Users\GuarinD\Documents\GitHub\Face_and_Gestures_2020\data\Features2d_BBP.csv", index_col = 0)
#Data_3D.pop('Unnamed: 0');
#Data_2D.pop('Unnamed: 0');

In [31]:
subjects = ['NF12', 'NF13', 'NF14', 'NF15', 'NF16', 'NF17', 'NF18', 'NF19', 'NF20', 'NF21', 'NF22', 'NF23', 'NF24', 'NF26', 'PD01', 'PD02', 'PD03', 'PD04', 'PD05', 'PD06', 'PD07', 'PD08']
healthy = ['NF12', 'NF13', 'NF14', 'NF15', 'NF16', 'NF17', 'NF18', 'NF19', 'NF20', 'NF21', 'NF22', 'NF23','NF24', 'NF26']
patients = ['PD01', 'PD02', 'PD03', 'PD04', 'PD05', 'PD06', 'PD07', 'PD08']

# number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 200, num = 50)]
# number of features at every split
max_features = ['auto','log2', None]

# max depth
max_depth = [int(x) for x in np.linspace(1, 20, num = 20)]
max_depth.append(None)

criterion = ['gini', 'entropy']
# create random grid
random_grid = {
'n_estimators': n_estimators,
'max_features': max_features,
'max_depth': max_depth,
'criterion' : criterion
}

estimator = RandomForestClassifier()

Data = Data_3D.copy(deep=True)

YPRED = []
YTEST = []
acc = []
conf_mat = []
pred_status = []

true_labels=[1,]

disease_status = []
conf_matrix_totals =np.zeros((2,2))
conf_matrix_patients = np.zeros((2,2))
for s in subjects:
    healthy = ['NF12', 'NF13', 'NF14', 'NF15', 'NF16', 'NF17', 'NF18', 'NF19', 'NF20', 'NF21', 'NF22', 'NF23', 'NF24', 'NF26']
    patients = ['PD01', 'PD02', 'PD03', 'PD04', 'PD05', 'PD06', 'PD07', 'PD08']

    #get data for all subjects except 's'
    values_ = Data.loc[Data.Subject_ID != s].values    
    X = values_[:,1:18]
    y = values_[:,18]
    
    custom_index = []
    TempDF = pd.DataFrame(values_, columns = Data.columns)
    if 'NF' in s:
        idx = healthy.index(s)
        healthy.pop(idx)
        
        rand_healthy = secrets.SystemRandom().sample(healthy, 6)
        rand_healthy = np.asarray(rand_healthy).reshape(3,2)
        rand_patients = secrets.SystemRandom().sample(patients, 6)
        rand_patients = np.asarray(rand_patients).reshape(3,2)
        for hh,pp in zip(rand_healthy,rand_patients):
            val_subjects = np.concatenate((hh,pp))
            training_index = TempDF[~TempDF.Subject_ID.isin(val_subjects)].index.values.astype(int)
            val_index = TempDF[TempDF.Subject_ID.isin(val_subjects)].index.values.astype(int)
        
            custom_index.append( (training_index, val_index) )

    else:
        idx = patients.index(s)
        healthy.pop(idx)
        rand_healthy = secrets.SystemRandom().sample(healthy, 6)
        rand_healthy = np.asarray(rand_healthy).reshape(3,2)
        rand_patients = secrets.SystemRandom().sample(patients, 6)
        rand_patients = np.asarray(rand_patients).reshape(3,2)
        for hh,pp in zip(rand_healthy,rand_patients):
            val_subjects = np.concatenate((hh,pp))
            training_index = TempDF[~TempDF.Subject_ID.isin(val_subjects)].index.values.astype(int)
            val_index = TempDF[TempDF.Subject_ID.isin(val_subjects)].index.values.astype(int)
        
            custom_index.append( (training_index, val_index) )
        

#     rfc_random = RandomizedSearchCV(estimator = estimator, param_distributions = random_grid, n_iter = 100, cv =custom_index, verbose=False, random_state=0, n_jobs = -1)
#     # Fit the model
#     rfc_random.fit(X, y.astype(np.float))

    
#     #generate a model with best parameters
#     estimator = RandomForestClassifier(**rfc_random.best_params_, n_jobs=-1)
    estimator = RandomForestClassifier(n_jobs=-1)
    estimator.fit(X,y.astype(np.float))
    #get data for subject 's'
    values = Data.loc[Data.Subject_ID == s].values    
    X_test = values[:,1:18]
    y_test = values[:,18]
    
    
    
    #evalues best model for subject s
    y_pred = estimator.predict(X_test)
#     #print(best_estimator.feature_importances_)
#     print(confusion_matrix(y_test.astype(np.float),y_pred))
#     print(classification_report(y_test.astype(np.float),y_pred))
#     print(accuracy_score(y_test.astype(np.float), y_pred))
    
    YPRED.append(y_pred)
    YTEST.append(y_test.astype(np.float))
    acc.append(accuracy_score(y_test.astype(np.float), y_pred))
    
    cm = confusion_matrix(y_test.astype(np.float),y_pred)
    if len(cm)==1:
        if 'NF'in s:
            conf_m = np.zeros((2,2))
            conf_m[0,0]=cm[0][0]
        else:
            conf_m = np.zeros((2,2))
            conf_m[1,1]=cm[0][0]
    else:
        conf_m = cm      
        
        
    conf_mat.append(conf_m)
    conf_matrix_totals = conf_matrix_totals+conf_m
    
    
    disease_status.append(0 if np.mean(y_pred)<=0.5 else 1)
    
    if 'NF' in s:
        if disease_status[-1] == 0:
            pred_status.append(1)
        else:
            pred_status.append(0)            
    else:
        if disease_status[-1] == 1:
            pred_status.append(1)
        else:
            pred_status.append(0)
            
            
    if 'NF' in s:
        if disease_status[-1] == 0:
            conf_matrix_patients = conf_matrix_patients + np.array([[1,0],[0,0]])
        else:
            conf_matrix_patients = conf_matrix_patients + np.array([[0,1],[0,0]])
            
    else:
        if disease_status[-1] == 1:
            conf_matrix_patients = conf_matrix_patients + np.array([[0,0],[0,1]])
        else:
            conf_matrix_patients = conf_matrix_patients + np.array([[0,0],[1,0]])
        


print(conf_matrix_totals,conf_matrix_patients,np.mean(np.asarray(pred_status))*100)  

[[51. 17.]
 [23. 17.]] [[11.  3.]
 [ 5.  3.]] 63.63636363636363


In [15]:
for s,p in zip(subjects,disease_status):
    print(s+'-'+str(p))


NF12-0
NF13-0
NF14-0
NF15-0
NF16-0
NF17-0
NF18-0
NF19-1
NF20-0
NF21-0
NF22-0
NF23-0
NF24-0
NF26-1
PD01-1
PD02-0
PD03-0
PD04-0
PD05-1
PD06-0
PD07-1
PD08-1


In [454]:
YPRED

[array([0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1.]),
 array([1., 1., 0., 1., 0., 1., 1., 1., 1., 1.]),
 array([0., 0.]),
 array([0., 1., 1., 1., 1., 0., 1., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 0., 1., 1., 1., 1., 0., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 1., 0., 0., 1.])]

In [342]:
conf_matrix_totals

array([[403., 139.],
       [203.,   9.]])

In [386]:
disease_status = 0 if np.sum(np.abs(y_pred-y_test))/len(y_pred)<0.5 else 1
disease_status

1

In [391]:
disease_status = 0 if np.mean(y_pred)<=0.5 else 1
disease_status

0

In [404]:
Data.loc[Data.Subject_ID != s]

Subject_ID  Duration    max_TB  max_TB_vel  min_TB_vel  Label
31        NF13  0.219880  0.904690    0.175109   -0.156268    0.0
32        NF13  0.179902  0.723334    0.133691   -0.140568    0.0
33        NF13  0.199891  0.645300    0.175866   -0.181723    0.0
34        NF13  0.179902  0.670724    0.183860   -0.112598    0.0
35        NF13  0.179902  0.677409    0.142000   -0.147448    0.0
36        NF13  0.199892  0.673699    0.149922   -0.159912    0.0
37        NF13  0.199892  0.689873    0.150833   -0.117375    0.0
38        NF13  0.219881  0.795321    0.189360   -0.157307    0.0
39        NF13  0.199892  0.888597    0.189405   -0.143860    0.0
40        NF13  0.199892  0.730202    0.151689   -0.185065    0.0
41        NF13  0.199892  0.706274    0.194615   -0.159866    0.0
42        NF13  0.199892  0.795625    0.216735   -0.152873    0.0
43        NF13  0.219881  0.719855    0.133685   -0.116898    0.0
44        NF13  0.219881  0.645350    0.104312   -0.119481    0.0
45        NF13  0.219882  0.702438    0.123228   -0.116213    0.0
46        NF13  0.259860  0.796837    0.117947   -0.129669    0.0
47        NF13  0.199893  0.650520    0.109976   -0.105332    0.0
48        NF13  0.219882  0.683731    0.127921   -0.115064    0.0
49        NF13  0.199893  0.753446    0.113138   -0.098094    0.0
50        NF13  0.219882  0.668349    0.075450   -0.113687    0.0
51        NF13  0.199893  0.585246    0.104010   -0.107064    0.0
52        NF13  0.219882  0.751557    0.130325   -0.142663    0.0
53        NF13  0.199893  0.664869    0.130551   -0.122090    0.0
54        NF13  0.199893  0.614747    0.108113   -0.120261    0.0
55        NF13  0.219883  0.705168    0.131388   -0.109110    0.0
56        NF13  0.219883  0.664279    0.110857   -0.119049    0.0
57        NF13  0.199893  0.785267    0.160070   -0.102364    0.0
58        NF13  0.239872  0.938757    0.145272   -0.157890    0.0
59        NF13  0.219883  0.742529    0.140837   -0.107821    0.0
60        NF13  0.219883  0.624858    0.076884   -0.109008    0.0
..         ...       ...       ...         ...         ...    ...
724       PD07  0.233235  1.078572    0.134181   -0.125566    1.0
725       PD07  0.199742  0.887507    0.110002   -0.107602    1.0
726       PD07  0.199778  0.822778    0.081648   -0.092993    1.0
727       PD07  0.216764  0.675096    0.056948   -0.060172    1.0
728       PD07  0.199973  0.654928    0.058051   -0.056509    1.0
729       PD07  0.233338  0.842376    0.093286   -0.094482    1.0
730       PD07  0.216606  0.810882    0.091626   -0.078209    1.0
731       PD07  0.199902  0.808942    0.077053   -0.080191    1.0
732       PD07  0.216435  0.650574    0.056623   -0.054947    1.0
733       PD07  0.199899  0.828795    0.093833   -0.095308    1.0
734       PD07  0.216625  0.921627    0.113570   -0.148537    1.0
735       PD07  0.199863  0.786002    0.063447   -0.092135    1.0
736       PD07  0.216311  0.883991    0.108400   -0.087678    1.0
737       PD07  0.216477  0.628639    0.060881   -0.092566    1.0
738       PD08  0.333257  1.284595    0.307937   -0.321951    1.0
739       PD08  0.333382  1.242796    0.303154   -0.314346    1.0
740       PD08  0.282678  1.552640    0.386902   -0.441897    1.0
741       PD08  0.333006  1.541502    0.325053   -0.446402    1.0
742       PD08  0.283274  1.710146    0.442811   -0.464556    1.0
743       PD08  0.299970  1.591717    0.366353   -0.472655    1.0
744       PD08  0.249622  1.510962    0.319204   -0.493197    1.0
745       PD08  0.249616  1.559730    0.410798   -0.464806    1.0
746       PD08  0.249839  1.258734    0.343888   -0.356121    1.0
747       PD08  0.282857  1.526736    0.342935   -0.480896    1.0
748       PD08  0.216484  1.132161    0.395713   -0.294018    1.0
749       PD08  0.233158  1.163769    0.270528   -0.363939    1.0
750       PD08  0.216341  1.177691    0.316590   -0.278005    1.0
751       PD08  0.416151  1.546112    0.230412   -0.325542    1.0
752       PD08  0.249613  1.338057    0.3316

In [414]:
time = np.arange(len(y))
len(np.diff(time)), len(time)

(102, 103)

In [424]:
y[:]

array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
       1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.